FROM node:23-alpine

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm install -g npm@latest
RUN npm install && npm install -g nodemon

EXPOSE 4001

CMD [ "npm","run","dev" ]
